# Generated by Django 5.0 on 2023-12-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender_auth_app', '0003_alter_sender_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='sender',
            name='password',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='sender',
            name='password2',
            field=models.CharField(max_length=16),
        ),
    ]
