# Generated by Django 5.0.1 on 2024-01-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender_auth_app', '0004_alter_sender_email_alter_sender_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
