# Generated by Django 5.0.1 on 2024-01-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender_auth_app', '0005_sender_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
