# Generated by Django 5.0.1 on 2024-02-05 16:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender_auth_app', '0008_alter_sender_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
