# Generated by Django 5.0.1 on 2024-06-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender_auth_app', '0009_alter_sender_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
