# Generated by Django 4.2.7 on 2023-11-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reciever',
            fields=[
                ('bank_account', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=20)),
                ('reference_id', models.CharField(max_length=20, unique=True)),
                ('legal_business_name', models.CharField(max_length=250)),
                ('business_type', models.CharField(default='partnership', max_length=250)),
                ('contact_name', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('subcategory', models.CharField(max_length=250)),
                ('street1', models.CharField(max_length=250)),
                ('street2', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=250)),
                ('payment', models.CharField(blank=True, max_length=10, null=True)),
                ('percentage', models.CharField(blank=True, max_length=4, null=True)),
                ('pan', models.CharField(max_length=100)),
                ('gst', models.CharField(max_length=100)),
                ('razor_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
