# Generated by Django 5.0.1 on 2024-02-09 17:20

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('upi_link', models.BooleanField(default=True)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('reference_id', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('callback_url', models.URLField(blank=True, null=True)),
                ('callback_method', models.CharField(default='get', max_length=200)),
                ('payment_link_id', models.CharField(blank=True, max_length=200, null=True)),
                ('paid_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('paid_plink_id', models.CharField(blank=True, max_length=200, null=True)),
                ('short_url', models.URLField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=200, null=True)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecieversGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('photo_url', models.CharField(blank=True, max_length=5000, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=10, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reciever',
            fields=[
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(blank=True, null=True)),
                ('main_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('type', models.CharField(default='route', max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=20, null=True)),
                ('legal_business_name', models.CharField(max_length=250)),
                ('business_type', models.CharField(default='individual', max_length=250)),
                ('contact_name', models.CharField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(blank=True, max_length=250, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=250, null=True)),
                ('street1', models.CharField(blank=True, max_length=250, null=True)),
                ('street2', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=250, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=250, null=True)),
                ('payment', models.CharField(blank=True, max_length=10, null=True)),
                ('percentage', models.CharField(default='0', max_length=4)),
                ('pan', models.CharField(blank=True, max_length=100, null=True)),
                ('gst', models.CharField(blank=True, max_length=100, null=True)),
                ('razor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tnc_accepted', models.BooleanField(default=True)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(default='route', max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=250, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('photo_url', models.CharField(blank=True, max_length=5000, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reciever_recieversgroup', to='route.recieversgroup')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_history_recieversgroup', to='route.recieversgroup')),
            ],
        ),
    ]
