# Generated by Django 4.2.7 on 2023-11-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciever',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
