# Generated by Django 5.0.1 on 2024-02-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciever',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
