# Generated by Django 5.0.1 on 2024-05-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_alter_reciever_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieversgroup',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
