# Generated by Django 5.0.1 on 2024-06-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_alter_recieversgroup_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciever',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
