# Generated by Django 4.2.7 on 2023-12-17 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_stakeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductConfigDetails',
            fields=[
                ('main_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('tnc_accepted', models.CharField(max_length=100)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('linked_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
