# Generated by Django 4.2.7 on 2023-12-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_productconfigdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productconfigdetails',
            name='tnc_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
