# Generated by Django 4.2.7 on 2023-12-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_alter_productconfigdetails_tnc_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciever',
            name='ifsc_code',
        ),
        migrations.AddField(
            model_name='productconfigdetails',
            name='account_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productconfigdetails',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productconfigdetails',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
