# Generated by Django 5.0 on 2023-12-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0007_alter_reciever_business_type_alter_reciever_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='pan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='postal_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='state',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='street',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
