# Generated by Django 5.0 on 2023-12-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0008_alter_stakeholder_city_alter_stakeholder_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='linked_account',
        ),
        migrations.AddField(
            model_name='reciever',
            name='account_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='reciever',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reciever',
            name='product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reciever',
            name='product_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reciever',
            name='tnc_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ProductConfigDetails',
        ),
        migrations.DeleteModel(
            name='Stakeholder',
        ),
    ]
