# Generated by Django 5.0 on 2023-12-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('route', '0009_remove_stakeholder_linked_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciever',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='reciever_groups', related_query_name='reciever_group', to='auth.group', verbose_name='Groups'),
        ),
        migrations.AlterField(
            model_name='reciever',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='reciever_user_permissions', related_query_name='reciever_user_permission', to='auth.permission', verbose_name='User permissions'),
        ),
    ]
