# Generated by Django 5.0 on 2023-12-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0010_alter_reciever_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecieversGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='reciever',
            options={},
        ),
        migrations.AlterModelManagers(
            name='reciever',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='reciever',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='reciever',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='reciever',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='reciever',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='reciever',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='reciever',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='reciever',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='reciever',
            name='password',
        ),
        migrations.RemoveField(
            model_name='reciever',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='reciever',
            name='username',
        ),
        migrations.AlterField(
            model_name='reciever',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='reciever_recievergroups', to='route.recieversgroup'),
        ),
    ]
