# Generated by Django 5.0 on 2023-12-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0011_recieversgroup_alter_reciever_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_link', models.BooleanField(default=True)),
                ('amount', models.CharField(max_length=100)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('reference_id', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('callback_url', models.URLField(blank=True, null=True)),
                ('callback_method', models.CharField(default='get', max_length=200)),
            ],
        ),
    ]
