# Generated by Django 5.0 on 2023-12-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0016_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieversgroup',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
