# Generated by Django 5.0.1 on 2024-01-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0021_alter_reciever_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciever',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recieversgroup',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
