# Generated by Django 5.0.1 on 2024-01-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0022_reciever_photo_url_recieversgroup_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciever',
            name='photo_url',
            field=models.URLField(blank=True, max_length=50000, null=True),
        ),
    ]
