# Generated by Django 5.0.1 on 2024-01-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0026_remove_reciever_groups_reciever_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciever',
            name='photo_url',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
