# Generated by Django 5.0.1 on 2024-01-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0028_alter_reciever_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieversgroup',
            name='photo_url',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
