# Generated by Django 5.0.1 on 2024-01-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0029_alter_recieversgroup_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reciever',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recieversgroup',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recieversgroup',
            name='transaction_status',
            field=models.BooleanField(default=False),
        ),
    ]
