# Generated by Django 5.0.1 on 2024-01-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0032_remove_recieversgroup_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reciever',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='reciever',
            name='reference_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
