# Generated by Django 5.0.1 on 2024-01-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0033_alter_payment_reference_id_alter_reciever_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciever',
            name='percentage',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
