# Generated by Django 5.0.1 on 2024-01-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0034_alter_reciever_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recieversgroup',
            name='total_amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
