# Generated by Django 5.0.1 on 2024-02-05 16:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0035_recieversgroup_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciever',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='recieversgroup',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
